### ISSUE TITLE
Cambios recientes en API

### ISSUE THREAD

**Issue by ghost** [conekta/conekta-python#21]
Qué tal equipo Conekta,

Tengo algunas dudas acerca de unos cambios que  hemos notado en nuestra empresa con respecto al funcionamiento del API, una parte de los cargos los hacíamos por medio de una función llamada.

`conekta.Charge.create`

Sin embargo esa función a pesar de generar el cobro ya no aparece en la documentación, notamos que cambiaron los request y ahora se maneja como una 

`conekta.Order.create`

En este caso vemos, que el objeto a enviar cambia considerablemente y ahora la propiedad principal en vez de una tarjeta espera `payment_method` y dentro de ella definir que es de tipo tarjeta.

Nunca notamos el cambio de versión debido a que no vemos un log update por parte de Conekta y eso nos afectaría bastante en producción.

Mis preguntas acerca de este tema es:

1. El método en Python de `conekta.Charge.create` aún seguirá en las siguientes versiones o estará como deprecated? .
2. Por qué el atributo de `unit_price` es de tipo [String, Integer]? Si quiero manejar decimales en este caso es confuso tener que usar 100050 para representar "100.50"
3. Hasta que versión la API de PHP descartará el objeto de "card" directamente en el cargo.

Saludos.

**Comment by leofischer** [comment]
Hola @ulisesmarx,

1. El método en Python de `conekta.Charge.create` aún seguirá en las siguientes versiones o estará como deprecated? 

  El flujo de cargos está siendo deprecado y para aprovechar OxxoPay tendrán que ocupar la nueva versión. Estaremos haciendo unos cambios en las proximas 2 semanas para simplificar la lógica de re-intentos, pero cualquier comentario al respecto avisanos para tomarla en consideración.

2.  Por qué el atributo de `unit_price` es de tipo [String, Integer]? Si quiero manejar decimales en este caso es confuso tener que usar 100050 para representar "100.50"

  Independiente de si mandas String o Integer el valor deberia de representar el monto en centavos, te va arrojar un error de validación "100.50" en la nueva versión de hecho.  Ahorita tenemos pendiente lanzar un cambio para hacer este mensaje de error más claro. 
 
3.  Hasta que versión la API de PHP descartará el objeto de "card" directamente en el cargo.

  Igual como el punto unos, el objecto card tal cual está depcrecado y no existe en la nueva versión, sino payment_source (para en el futuro poder aceptar otros tipos de pago). Si ya tienes cards en Conekta, simplemente será el payment_source en la proxima versión.  Cualquier comentario o duda está bien bienvenido.

Saludos,

-Leo

**Comment by ulisesmarx** [comment]
Gracias por la pronta respuesta Leo, tomaremos en consideración todo esto para hacer los cambios necesarios antes de pasar a productivo.

Estaremos al pendiente de cualquier otra actualización, sobre todo el del precio, ya que aun los chicos están un poco confundidos con esa parte.

Saludos y gracias!

**Comment by ulisesmarx** [comment]
Con la actualización los chicos me mandan este error:
`'module' object has no attribute 'Customer'
Los comandos usados :
`pip install --upgrade conekta`

Algun consejo?

Saludos

**Comment by KarlaRobinson** [comment]
Hola @ulisesmarx,
Han podido usar la librería? Si aun están teniendo dificultad, les pedimos que nos mandan un correo a soporte@conekta.com para revisar tu integración y ayudarlos de forma mas rápido!

Saludos,
-Karla

**Comment by sonibaba** [comment]
hola que tal, recien use la ap de conekta y no eh podido imprimir el error de la orden en python, si y con la documentacion me dice que no es un atributo. por favor si tienen codigo pasenlo por favor

**Comment by leofischer** [comment]
Hola @sonibaba,

Lo estoy revisando y parece que tienes razón, me parece que quedaba desde una versión anterior.  De momento ver el error completo ocupando `str(e)`, o acceder directamente al mensaje ocupando algo como `e.error_json['details'][0]['message']`.  Ahorita voy a abrir un PR para actualizar el Readme y también la documentación del sitio, revisaré si agregamos un método helper para acceder directamente a este atributo mediate `e.message`

**Comment by leofischer** [comment]
@sonibaba - aquí viene el PR por si quieres echarle un ojo
