### ISSUE TITLE
Problemas con Update subscription

### ISSUE THREAD

**Issue by Rhombeus** [conekta/conekta-python#22]
customer.subscription.update({'plan':'otro_plan'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../conekta/__init__.py", line 192, in update
    return self.load_via_http_request(uri, 'PUT', params, api_key=api_key)
  File ".../conekta/__init__.py", line 148, in load_via_http_request
    response = self.load_url(url, method=method, params=params, api_key=api_key)
  File ".../conekta/__init__.py", line 111, in load_url
    response = cls.build_http_request(method, path, params, _api_key = api_key)
  File ".../conekta/__init__.py", line 101, in build_http_request
    raise ResourceNotFoundError(json.loads(body))
conekta.ResourceNotFoundError: {u'log_id': u'58cc2f4bdba34d28c5899771', u'object': u'error', u'type': u'resource_not_found_error', u'details': [{u'debug_message': u'The route requested does not exist.', u'message': u'The route requested does not exist.', u'code': u'conekta.errors.resource_not_found.unknown_route'}]}

**Comment by Janee** [comment]
Hola @Rhombeus,
¿puedes enviarnos este caso a soporte@conekta.com añadiendo el correo de tu cuenta Conekta y tu código para poder revisar tus logs y hacer una prueba?

¡Bonito día!
