### ISSUE TITLE
"Shipment is needed for physical goods." error when processing card payment

### ISSUE THREAD

**Issue by panzerfausten** [conekta/conekta-python#25]
Hi guys,

so I am using the python library to charge via credit card.
I get this error when trying to charge it:

> {u'code': u'parameter_validation', u'validation_error': None, u'object': u'error', u'param': None, u'message_to_purchaser': u'**Shipment is needed for physical goods.**', u'message': u'Shipment is needed for physical goods.', u'type': u'parameter_validation_error'}

This is my JSON:

> 
> {
>   "customer": {
>     "corporation_name": "",
>     "logged_in": true,
>     "email": ""
>   },
>   "line_items": [
>     
>   ],
>   "referenceId": "590cbb0ca75c4d12ebdc6cf2",
>   "description": "Compra de ropa de mujer",
>   "shipping_lines": [
>     {
>       "amount": 1500,
>       "carrier": "mi compania"
>     }
>   ],
>   "shipping_contact": {
>     "phone": "+52181818181",
>     "address": {
>       "city": "Cuahutemoc",
>       "residential": true,
>       "street1": "Calle 123 int 2 Col. Chida",
>       "state": "Ciudad de Mexico",
>       "postal_code": "06100",
>       "country": "MX"
>     },
>     "receiver": "Bruce Wayne"
>   },
>   "currency": "MXN",
>   "amount": 67500,
>   "billing_address": {
>     
>   },
>   "details": {
>     "line_items": [
>       {
>         "sku": "BLU-BON-001-2",
>         "name": "Blusa bonita",
>         "description": "Esta blusa esta muy bonita",
>         "unit_price": 325,
>         "type": "clothing",
>         "quantity": 1
>       },
>       {
>         "sku": "BLU-BON-001-3",
>         "name": "Blusa bonita",
>         "description": "Esta blusa esta muy bonita",
>         "unit_price": 350,
>         "type": "clothing",
>         "quantity": 1
>       }
>     ],
>     "billing_address": {
>       "city": "ensenada",
>       "name": "Darien",
>       "lastname": "Miranda",
>       "street2": "interior 5",
>       "email": "asd@hotmail.com",
>       "phone": "6688888888",
>       "state": "baja california",
>       "notes": "",
>       "street1": "1st street",
>       "cp": "22880",
>       "company": ""
>     },
>     "name": "Darien Alberto",
>     "phone": "6681172376",
>     "shipment": {
>       "city": "ensenada",
>       "name": "Darien",
>       "lastname": "Miranda",
>       "street2": "interior 5",
>       "email": "asd@hotmail.com",
>       "phone": "6688888888",
>       "state": "baja california",
>       "notes": "",
>       "street1": "1st street",
>       "cp": "22880",
>       "company": ""
>     },
>     "email": "asd@hotmail.com"
>   },
>   "shipment": {
>       "city": "ensenada",
>       "name": "Darien",
>       "lastname": "Miranda",
>       "street2": "interior 5",
>       "email": "asd@hotmail.com",
>       "phone": "6688888888",
>       "state": "baja california",
>       "notes": "",
>       "street1": "1st street",
>       "cp": "22880",
>     "company": ""
>   },
>   "card": "tok_test_visa_4242"
> }

I am not sure how to specify the shipping details and the documentation is not clear about it: https://developers.conekta.com/api?language=python#order

thank you!

-Darien

**Comment by Janee** [comment]
Hello @panzerfausten 
Can you please try with this JSON:

```json
{
      "line_items": [{
          "name": "Tacos",
          "unit_price": 10000,
          "quantity": 12
      }],
	  "shipping_lines": [{
		  "amount": 1500,
		  "carrier": "mi compania"
	  }],
	"shipping_contact": {
		"phone": "8181818181",
		"address": {
			"city": "Cuahutemoc",
			"residential": true,
			"street1": "Calle 123 int 2 Col. Chida",
			"state": "Ciudad de Mexico",
			"postal_code": "06100",
			"country": "MX"
		},
		"receiver": "Bruce Wayne"
	},
      "currency": "MXN",
      "customer_info": {
          "name": "Juan Péréz",
		  "email": "something@conekta.com",
		  "phone": "8180889769"
      },
	"charges":[{
          "payment_method": {
              "type": "oxxo_cash"		  
		  }
      }],
	"metadata":{"agency": "value"}
  }
```

I think is only a syntax error. Please confirm you are using the API *2.0*.

**Comment by panzerfausten** [comment]
sure,

I tried your JSON code and now I get the following error:

> {u'code': u'invalid_payment_type', u'validation_error': None, u'object': u'error', u'param': u'payment_type', u'message_to_purchaser': u'Payment method invalid or missing. Accepted values are: card , cash or bank.', u'message': u'Payment method invalid or missing. Accepted values are: card , cash or bank.', u'type': u'parameter_validation_error'}

**Comment by Janee** [comment]
Can you please send us an email to contacto@conekta.com with your request and your Conekta account? @panzerfausten

**Comment by panzerfausten** [comment]
@Janee  Just sent the email, thanks.

**Comment by panzerfausten** [comment]
@Janee  The error was my implementation, I was using the old charge instead of order method.  You can close this issue and #26 now 👍
