### ISSUE TITLE
SSLEOFError: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by oortega** [conekta/conekta-python#43]
Hola,

Recientemente obtengo el error mencionado, ya intenete actualizar request como meciona aqui: 
https://github.com/requests/requests/issues/3006#issuecomment-255431145 pero el problema persiste.

En algunas ocasiones genera este error, alguna idea del problema?

**TraceBack**

```
`SSLEOFError: EOF occurred in violation of protocol (_ssl.c:581)
  File "celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "wisp/tasks.py", line 637, in generar_facturas_automaticamente
    factura_cliente = crear_nueva_factura(empresa, cliente, cliente.user.perfilusuario.descuento, user_admin[0])
  File "wisp_factura/views.py", line 2293, in crear_nueva_factura
    recibo_oxxo = generar_recibo_oxxo(nueva_factura, empresa)
  File "wisp_cliente/views.py", line 767, in generar_recibo_oxxo
    "type": "oxxo_cash"
  File "conekta/__init__.py", line 201, in create
    return cls(cls.load_url(endpoint, method='POST', params=params, api_key=api_key))
  File "conekta/__init__.py", line 112, in load_url
    response = cls.build_http_request(method, path, params, _api_key = api_key)
  File "conekta/__init__.py", line 84, in build_http_request
    headers, body = request(absolute_url, method, headers=HEADERS, body=json.dumps(params))
  File "httplib2/__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "httplib2/__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "httplib2/__init__.py", line 1319, in _conn_request
    conn.connect()
  File "httplib2/__init__.py", line 1069, in connect
    self.ssl_version, self.host)
  File "httplib2/__init__.py", line 97, in _ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=hostname)
  File "gevent/_sslgte279.py", line 68, in wrap_socket
    _context=self)
  File "gevent/_sslgte279.py", line 270, in __init__
    raise x`
```

**paquetes instalados:**
requests==2.12.4
pyOpenSSL==18.0.0
ndg-httpsclient==0.5.0
conekta==2.3.4
cryptography==2.2.2
pyasn1==0.4.3

Gracias por la ayuda.

**Comment by eduenriquez** [comment]
Asegurate de que todos los requests usen TLSv1.2, que tu servidor tenga soporte para el protocolo, parece que requests tiene problemas con apis que pasan por vpn's como explican aqui https://github.com/requests/requests/issues/3006#issuecomment-344247902 déjame revisar el issue con la parte de infra del api

**Comment by oortega** [comment]
disculpa pero como reviso esto?: **_Asegurate de que todos los requests usen TLSv1.2, que tu servidor tenga soporte para el protocolo_**

**Comment by eduenriquez** [comment]
@oortega ya confirme con infraestructura que este error no es por pasar la conexión por los balanceadores del api. 
con que frecuencia obtienes ese error ? 
podrias hacer upgrade de la lbreria a la latest ?; es decir la version 2.19 https://pypi.org/project/requests/

**Comment by oortega** [comment]
digamos que 1 de cada 10. Este error igual me pasa con otras API por ejemplo Payu.

**Comment by JoValo** [comment]
Hola @oortega el problema persiste?

**Comment by leofischer** [comment]
@oortega - sigues con este problema?  Sino para cerrar este issue.  Si está pasando igual con otros proveedores me suena ser algo más de red o algún agente de seguridad.  Veo casos parecidos aquí  https://github.com/psf/requests/issues/3605 y https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol, pero nada conclusivo suponiendo que está bien instalado ndg-httpsclient y pyopenssl.

**Comment by leofischer** [comment]
Voy a cerrar este issue de momento, nos pueden contactar si vuelva a ocurrir
