### ISSUE TITLE
[Question] Find charges from subscription

### ISSUE THREAD

**Issue by giovannyreyeso** [conekta/conekta-python#47]
Hi!. i was searching in docs about how i can get a charges from a subscription. i try Order.where and pass "customer id" but not worked.

In the documentation not exist a clear way for do a search charges from subscription.

**Comment by JoValo** [comment]
Hi @giovannyreyeso!
You can try this:
```
#this return a pagination object
orders = conekta.Order.where({'customer_info.customer_id': 'customer_id'})

if (orders.has_more):
  orders.next()
  #TO-DO
else:
  orders.data
  #TO-DO
```

**Comment by giovannyreyeso** [comment]
Thanks! i will check this solution
