### ISSUE TITLE
conekta.errors.processing.undefined method credit_commission for nil:NilClass

### ISSUE THREAD

**Issue by elessar93** [conekta/conekta-python#50]
Al intententar hacer una orden con tarjeta de credito me regresa este erro, también al crear la orden con oxxo(oxxo_comission) o con spei me genera un error parecido 

orden que envio
{'currency': 'MXN', 'customer_info': {'customer_id': 'cus_2nJmd3HZ9y8zgEBov'}, 'charges': [{'payment_method': {'type': 'card', 'token_id': 'tok_test_visa_4242'}}], 'line_items': [{'name': 'Servicio de transporte de ague de 5 Mil', 'unit_price': 120000, 'quantity': 1}]}

error message que regresa
translation missing: undefined method `credit_commission' for nil:NilClass_purchaser

**Comment by silvaGarduno** [comment]
Hola @elessar93 .

Este es un ejemplo más completo, podrías intentar con esto por favor y ver si persiste el error:
{
	"line_items": [
		{
			"name": "Tacos",
			"unit_price": 100000,
			"description": "Replica prueba",
			"quantity": 1
		}
	],
	"shipping_lines": [
		{
			"amount": 0,
			"carrier": "FEDEX"
		}
	],
	"currency": "MXN",
	"customer_info": {
		"customer_id": "cus_2nJmd3HZ9y8zgEBov"
	},
	"shipping_contact": {
		"address": {
			"street1": "Calle 123, int 2",
			"postal_code": "06100",
			"country": "MX"
		}
	},
	"metadata": {
		"order_number": "1234567810"
	},
	"charges": [
		{
			"payment_method": {
				"type": "default"
			}
		}
	]
}


saludos

**Comment by elessar93** [comment]
Hola, gracias por contestar.

Cree la orden con estos nuevos parámetros y me sigue arrojando el mismo error 

translation missing: undefined method `credit_commission' for nil:NilClass_purchaser

**Comment by silvaGarduno** [comment]
Qué version de Python estas usando? la librería esta en la versión 2.5.1

**Comment by elessar93** [comment]
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
y la version de la libreria si es 2.5.1

**Comment by silvaGarduno** [comment]
@elessar93 

Podrías probar con python 3.8 y ver si te sigue dando el mismo error por favor

**Comment by elessar93** [comment]
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
[Clang 6.0 (clang-600.0.57)] on darwin me sigue apareceindo

**Comment by silvaGarduno** [comment]
Ok, veo que si te genera la orden, solo es que te regresa el error la librería, deja checar que esta pasando y si es problema de la librería se lanzara un "fix" para corregir el error

**Comment by elessar93** [comment]
Hola, intente consumir la api desde una petición con CURL y el api me regresa el mismo error 


curl -H "Accept: application/vnd.conekta-v2.0.0+json" \
>      -H "Content-type: application/json" \
>      -u key_6ik7cgjHhkWWJAHgfzTz7g: \
>      -X POST -d '{
>         "currency": "MXN",
>         "customer_info": {
>            "customer_id": "cus_2nJmd3HZ9y8zgEBov"
>         },
>        "line_items": [{
>            "name": "Box of Cohiba S1s",
>            "unit_price": 35000,
>            "quantity": 1
>        }],
>        "charges": [{
>            "payment_method": {
>                "type": "default"
>            }
>        }]
>        }' https://api.conekta.io/orders


{
  "details": [
    {
      "debug_message": "translation missing: en attribute undefined method `credit_commission' for nil:NilClass",
      "message": "translation missing: undefined method `credit_commission' for nil:NilClass_purchaser",
      "code": "conekta.errors.processing.undefined method `credit_commission' for nil:NilClass"
    }
  ],
  "object": "error",
  "type": "processing_error",
  "log_id": "5e683ffd431e722317543df1",
  "data": {
    "livemode": false,
    "amount": 35000,
    "currency": "MXN",
    "amount_refunded": 0,
    "customer_info": {
      "email": "rcardenas93@gmail.com",
      "phone": "803534095934",
      "name": "Rafael Cardenas",
      "corporate": false,
      "customer_id": "cus_2nJmd3HZ9y8zgEBov",
      "object": "customer_info"
    },
    "shipping_contact": {
      "address": {
        "street1": "Calle 123, int 2",
        "country": "mx",
        "residential": true,
        "object": "shipping_address",
        "postal_code": "06100"
      },
      "id": "ship_cont_2nL7wTC6cZ6Vojmoh",
      "object": "shipping_contact",
      "created_at": 0
    },
    "object": "order",
    "id": "ord_2nL7wTC6cZ6Vojmoi",
    "metadata": {},
    "created_at": 1583890429,
    "updated_at": 1583890429,
    "line_items": {
      "object": "list",
      "has_more": false,
      "total": 1,
      "data": [
        {
          "name": "Box of Cohiba S1s",
          "unit_price": 35000,
          "quantity": 1,
          "object": "line_item",
          "id": "line_item_2nL7wTC6cZ6Vojmof",
          "parent_id": "ord_2nL7wTC6cZ6Vojmoi",
          "metadata": {},
          "antifraud_info": {}
        }
      ]
    }
  }
}

**Comment by silvaGarduno** [comment]
@elessar93 puedes intentar de la siguiente forma por favor.

curl -H "Accept: application/vnd.conekta-v2.0.0+json" \
 -H "Content-type: application/json" \
 -u key_6ik7cgjHhkWWJAHgfzTz7g: \
 -X POST -d '{
    "currency": "MXN",
        "customer_info": {
          "name": "test node",
          "phone": "+5215555555555",
          "email": "jul@conekta.io"
        },
        "line_items": [{
          "name": "Box of Cohiba S1s",
          "unit_price": 35000,
          "quantity": 1
        }],
        "shipping_contact": {
            "phone": "55-5555-5555",
            "receiver": "Poli de la caseta",
            "between_streets": "Ahuehuetes y Arellanos",
            "address": {
                "street1": "Ahuehuetes",
                "street2": "Arellanos",
                "city": "Mexico",
                "state": "CDMX",
                "country": "Mexico",
                "postal_code": "11789",
                "object": "Gift",
                "residential": true
            }
        },
        "shipping_lines": [
            {
                "amount": 1500,
                "tracking_number": "098",
                "carrier": "Bus",
                "method": "run"
            }
        ],
        "charges": [{
          "payment_method": {
            "type": "card",
            "token_id": "tok_test_visa_4242"
          }
        }]
   }' https://api.conekta.io/orders

**Comment by elessar93** [comment]
Lo intente de esa manera y siguió mandando el mismo error, pero en el proceso se activo la cuenta y ya se pueden crear ordenes sin problema
