### ISSUE TITLE
Error while trying to install Conekta==2.2.1 with Python 3.7

### ISSUE THREAD

**Issue by JVegaB** [conekta/conekta-python#57]
### Steps to reproduce

1. With Python version 3 run `pip install conketa==2.2.1`.

### Expected behavior

The version in the metadata is `2.2.1`.

### Current behavior

The downloaded version have within the metadata 2.2

![holi](https://git.vauxoo.com/vauxoo/tanner/uploads/527caca6818921ba7045fe33d2685658/Screenshot_from_2020-12-02_11-42-17.png)

**Comment by fcarrero** [comment]
try with this version
[PaymentSource](https://pypi.org/project/conekta/2.6.2/)
