### ISSUE TITLE
Name error for class Checkout

### ISSUE THREAD

**Issue by iThinkEmo** [conekta/conekta-python#60]
Line (467) of `__init__.py` you name the class `Checkout`, but in line (470) it's been initialised as `super(Checkouts, self).__init__(*args, **kwargs)`, so when creating a checkout, the compiler responds with `NameError: name 'Checkouts' is not defined`.

**Comment by fcarrero** [comment]
se soluciona en la version 2.6.2
https://pypi.org/project/conekta/2.6.2/
