### ISSUE TITLE
checkout = conekta.Checkout.create({ TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by c4pcha** [conekta/conekta-python#67]
tengo un error con conekta 2.6.0, corregí el problema de la identación pero ahora tengo este otro problema.

checkout = conekta.Checkout.create({
TypeError: unhashable type: 'dict'

**Comment by fcarrero** [comment]
se libero la version https://pypi.org/project/conekta/2.6.2/
la cual limpia los errores en checkout model
