### ISSUE TITLE
SSLError al crear un cliente

### ISSUE THREAD

**Issue by hackaprende** [conekta/conekta-python#82]
Estoy siguiendo los pasos de Pagos únicos con Component https://developers.conekta.com/docs/componente-de-pago 

Pero al querer crear un cliente con esta librería me da un error:

`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.conekta.io', port=443): Max retries exceeded with url: /customers (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))`

El error no sucede si uso el código de la API:

```
import requests

url = "https://api.conekta.io/customers"

payload = { "corporate": False }
headers = {
    "accept": "application/vnd.conekta-v2.1.0+json",
    "Accept-Language": "es",
    "content-type": "application/json",
    "authorization": "Bearer key_MySecretKeyHere"
}

response = requests.post(url, json=payload, headers=headers)

print(response.text)
```

**Comment by fcarrero** [comment]
sigues con el error ?
